layout_spectrum: 0.7386079767725365
typography_spectrum: 0.2409441755384686
color:
  brandStrength: 0.3657330195778188
  lightness: 0.879379130829642
  saturation: 0.7187237467200929
  rhythmicContrast: 0.1966610336105459
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/493dc36f-1f3e-41d1-9b42-088fac2eacd9.png
analytics:
  google: UA-48907311-1
author:
  name: Headnet
  email: info@headnet.dk
logo: null
name: HEADNET
navigation:
  - name: What we are and do
    id: 5d00134f-e8df-46bc-bf2d-5ab917a66283
    type: content
  - name: Our beloved customers
    id: dde53552-dd72-4475-affa-5de9f6535326
    type: content
  - name: The magic team
    id: f80e15bd-4b9f-4b31-9e2d-efcb664609d9
    type: content
  - name: The board of directors
    id: 3800fd1b-2f21-4fcb-84e6-94d2924de523
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ef50a64d-01d7-4bc6-824c-63d836832ccf.png
title: HEADNET
content: []
description: WE TECH A MORE INTELLIGENT FUTURE
purpose:
  - type: contact
    url: 'tel:+4570229750'
    label: 'Call: +45 7022 9750'
  - type: contact
    url: 'mailto:info@headnet.dk'
    label: 'Mail: info@headnet.dk'
